app:
  jwt:
    secret-base64: "vS1hkIMbyF75F4RDglgO8GbFq0NFIKlPmRbyAhSoVtU="

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/convoquei
    username: convoquei
    password: convoquei
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: true

#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.hibernate.orm.jdbc.extract: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true