spring:
  application:
    name: convoquei-backend
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      add-mappings: false
  quartz:
    auto-startup: true

app:
  jwt:
    issuer: "convoquei-api"
    secret-base64: "base64-encoded-replace-me"
    access-token-minutes: 60
    refresh-token-days: 30