spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/convoquei
    username: convoquei
    password: convoquei
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false